services:
  ai-gateway:
    image: ai-gateway:0.1.3
    container_name: ai-gateway
    restart: unless-stopped
    env_file:
      - ai-gateway.env
    ports:
      - "8080:8080"
    volumes:
      - ./data:/data
